# Generated by Django 4.1.7 on 2023-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('material', models.CharField(max_length=255, verbose_name='Materiali')),
                ('size', models.CharField(max_length=255, verbose_name="O'lchami")),
                ('selling_price', models.PositiveIntegerField(verbose_name='Sotish narxi')),
                ('color', models.CharField(max_length=255, verbose_name='Rangi')),
                ('comment', models.CharField(max_length=255, verbose_name='Izoh')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Sotib olish narxi')),
                ('is_order', models.BooleanField(default=False, verbose_name='Buyurtma')),
                ('is_suite', models.BooleanField(default=False, verbose_name='Komplektmi')),
            ],
            options={
                'verbose_name': 'Mahslulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
