# Generated by Django 4.1.7 on 2023-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.TextField(default=''),
        ),
    ]
