# Generated by Django 4.1.7 on 2023-12-10 16:59

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_color_remove_product_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='img',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=' ', upload_to=apps.products.models.rename_image),
            preserve_default=False,
        ),
    ]
