# Generated by Django 4.1.7 on 2023-12-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sizes'),
        ('orders', '0002_alter_order_date_alter_order_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='order/images')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='is_notificated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('sizes', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
