# Generated by Django 4.1.7 on 2024-01-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('orders', '0006_orderimage_delete_orderimages_order_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.images'),
        ),
    ]
