# Generated by Django 4.1.7 on 2023-03-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderManagement',
        ),
    ]
