# Generated by Django 4.1.7 on 2023-03-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_providermanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
