# Generated by Django 4.1.7 on 2023-12-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='view_date',
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
