# Generated by Django 4.1.7 on 2023-12-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
