# Generated by Django 4.1.7 on 2023-03-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('material', models.CharField(max_length=255, verbose_name='Materiali')),
                ('size', models.CharField(max_length=255, verbose_name="O'lchami")),
                ('selling_price', models.PositiveIntegerField(verbose_name='Sotish narxi')),
                ('color', models.CharField(max_length=255, verbose_name='Rangi')),
                ('comment', models.CharField(max_length=255, verbose_name='Izoh')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Sotib olish narxi')),
                ('is_order', models.BooleanField(default=False, verbose_name='Buyurtma')),
                ('is_suite', models.BooleanField(default=False, verbose_name='Komplektmi')),
            ],
            options={
                'verbose_name': 'Mahslulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SuiteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Suite', to='product.product', verbose_name='Komplekt')),
            ],
            options={
                'verbose_name': 'Komplekt tarkibi',
                'db_table': 'set_connection',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Ombor',
                'db_table': 'stock',
            },
        ),
    ]
