# Generated by Django 4.1.7 on 2023-03-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='prixod',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='prixod',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='prixod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prixoditems',
            name='prixod',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellitem',
            name='sell',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Prixod',
        ),
        migrations.DeleteModel(
            name='PrixodItems',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='SellItem',
        ),
    ]
