# Generated by Django 4.1.7 on 2023-03-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('product', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_set',
            new_name='is_suite',
        ),
        migrations.CreateModel(
            name='SuiteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Suite', to='product.product', verbose_name='Komplekt')),
            ],
            options={
                'verbose_name': 'Komplekt tarkibi',
                'db_table': 'set_connection',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Ombor',
                'db_table': 'stock',
            },
        ),
    ]
