# Generated by Django 4.1.7 on 2023-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_is_set_product_is_suite_suiteitems_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='suiteitems',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
