# Generated by Django 4.1.7 on 2023-03-02 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_stock_price_alter_suiteitems_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.DateTimeField()),
                ('go_back', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'davomat',
                'verbose_name_plural': 'davomat',
                'db_table': 'timtable',
            },
        ),
    ]
