# Generated by Django 4.1.7 on 2023-03-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_timtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timtable',
        ),
    ]
