# Generated by Django 4.1.7 on 2023-12-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('branches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorga vozvrat',
                'verbose_name_plural': 'Xaridorga vozvrat',
            },
        ),
        migrations.CreateModel(
            name='Prixod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Prixod hujjati',
                'verbose_name_plural': 'Prixodlar',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchiga mahsulot qaytarish",
                'verbose_name_plural': "Ta'minotchiga mahsulot qaytarish",
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('discount', models.PositiveIntegerField(verbose_name='chegirma')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Sotuvlar',
                'verbose_name_plural': 'Sotuvlar',
            },
        ),
        migrations.CreateModel(
            name='Timtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('date', models.DateField(verbose_name='Sana')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'davomat hujjati',
                'verbose_name_plural': 'davomat hujjati',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Spisaniya',
                'verbose_name_plural': 'Spisaniya',
            },
        ),
        migrations.CreateModel(
            name='WriteOffItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.writeoff', verbose_name='Spisaniya')),
            ],
            options={
                'verbose_name': 'Spisaniya hujjati tarkibi',
                'verbose_name_plural': 'Spisaniya hujjati tarkibi',
            },
        ),
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Ishchilar maoshi',
                'verbose_name_plural': 'Ishchilar maoshi',
            },
        ),
        migrations.CreateModel(
            name='TimtableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.TimeField(verbose_name='Kelgan vaqti')),
                ('go_back', models.TimeField(verbose_name='Ketgan vaqti')),
                ('comment', models.TextField()),
                ('tim_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.timtable', verbose_name='Davomat hujjati')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'davomat hujjati tarkibi',
                'verbose_name_plural': 'davomat hujjati tarkibi',
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.sell', verbose_name='Sotuv hujjati')),
            ],
            options={
                'verbose_name': 'Sotuv tarkibi',
                'verbose_name_plural': 'Sotuv tarkibi',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
                ('provider_send_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.providersendback', verbose_name='tovar vozvrat')),
            ],
            options={
                'verbose_name': 'Taminotchiga vozvrat hujjati tarkibi',
                'verbose_name_plural': 'Taminotchiga vozvrat hujjati tarkibi',
            },
        ),
        migrations.CreateModel(
            name='ProviderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('prixod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.prixod', verbose_name='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchi bilan hiosb-kitob",
                'verbose_name_plural': "Ta'minotchi bilan hiosb-kitob",
            },
        ),
        migrations.CreateModel(
            name='PrixodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('prixod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.prixod', verbose_name='Prixod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Prixod tarkibi',
                'verbose_name_plural': 'Prixodlar tarkibi',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
            },
        ),
        migrations.CreateModel(
            name='PayOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassa kirim-chiqim',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.orders', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyutma tarkibi',
                'verbose_name_plural': 'Buyutmalar tarkibi',
            },
        ),
        migrations.CreateModel(
            name='CustomerSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('CustomerSendBack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.customersendback', verbose_name='tovar vozvrat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Xaridorga vozvrat hujjati tarkibi',
                'verbose_name_plural': 'Xaridorga vozvrat hujjati tarkibi',
            },
        ),
        migrations.CreateModel(
            name='CustomerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='verbose_name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.orders', verbose_name='buyurtma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorlar bilan hisob-kitob',
                'verbose_name_plural': 'Xaridorlar bilan hisob-kitob',
            },
        ),
    ]
