# Generated by Django 4.1.7 on 2023-12-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sizes'),
        ('receives', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_items', to='products.product'),
        ),
    ]
