# Generated by Django 4.1.7 on 2023-03-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('users', '__first__'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorga vozvrat',
                'verbose_name_plural': 'Xaridorga vozvrat',
                'db_table': 'take_back',
            },
        ),
        migrations.CreateModel(
            name='Prixod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Prixod hujjati',
                'verbose_name_plural': 'Prixodlar',
                'db_table': 'receive',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchiga mahsulot qaytarish",
                'verbose_name_plural': "Ta'minotchiga mahsulot qaytarish",
                'db_table': 'send_back',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Sotuvlar',
                'verbose_name_plural': 'Sotuvlar',
                'db_table': 'sell',
            },
        ),
        migrations.CreateModel(
            name='TimtableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.TimeField(verbose_name='Kelgan vaqti')),
                ('go_back', models.TimeField(verbose_name='Ketgan vaqti')),
            ],
            options={
                'verbose_name': 'davomat hujjati tarkibi',
                'verbose_name_plural': 'davomat hujjati tarkibi',
                'db_table': 'timtable_items',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('comment', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Spisaniya',
                'verbose_name_plural': 'Spisaniya',
                'db_table': 'write_off',
            },
        ),
        migrations.CreateModel(
            name='WriteOffItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.writeoff', verbose_name='Spisaniya')),
            ],
            options={
                'verbose_name': 'Spisaniya hujjati tarkibi',
                'verbose_name_plural': 'Spisaniya hujjati tarkibi',
                'db_table': 'written_off',
            },
        ),
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Ishchilar maoshi',
                'verbose_name_plural': 'Ishchilar maoshi',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Timtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'davomat hujjati',
                'verbose_name_plural': 'davomat hujjati',
                'db_table': 'timtable',
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.sell', verbose_name='Sotuv hujjati')),
            ],
            options={
                'verbose_name': 'Sotuv tarkibi',
                'verbose_name_plural': 'Sotuv tarkibi',
                'db_table': 'sell_item',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('provider_send_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.providersendback', verbose_name='tovar vozvrat')),
            ],
            options={
                'verbose_name': 'Taminotchiga vozvrat hujjati tarkibi',
                'verbose_name_plural': 'Taminotchiga vozvrat hujjati tarkibi',
                'db_table': 'sent_back',
            },
        ),
        migrations.CreateModel(
            name='ProviderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchi bilan hiosb-kitob",
                'verbose_name_plural': "Ta'minotchi bilan hiosb-kitob",
                'db_table': 'provider_management',
            },
        ),
        migrations.CreateModel(
            name='PrixodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('prixod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.prixod', verbose_name='Prixod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Prixod tarkibi',
                'verbose_name_plural': 'Prixodlar tarkibi',
                'db_table': 'receive_items',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('cash', models.IntegerField(default=0, verbose_name='Pul miqdori')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
                'db_table': 'penalty',
            },
        ),
        migrations.CreateModel(
            name='PayOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('cash', models.IntegerField(default=0, verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassa kirim-chiqim',
                'db_table': 'pay_office',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('cost', models.IntegerField(verbose_name='Narxi')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.orders', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyutma tarkibi',
                'verbose_name_plural': 'Buyutmalar tarkibi',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('CustomerSendBack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.customersendback', verbose_name='tovar vozvrat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Xaridorga vozvrat hujjati tarkibi',
                'verbose_name_plural': 'Xaridorga vozvrat hujjati tarkibi',
                'db_table': 'taken_back',
            },
        ),
        migrations.CreateModel(
            name='CustomerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Vaqti')),
                ('cash', models.PositiveIntegerField(default=0, verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorlar bilan hisob-kitob',
                'verbose_name_plural': 'Xaridorlar bilan hisob-kitob',
                'db_table': 'customer_management',
            },
        ),
    ]
