# Generated by Django 4.1.7 on 2023-03-02 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('product', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prixod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim hujjati',
                'verbose_name_plural': 'Kirimlar',
                'db_table': 'receive',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchiga mahsulot qaytarish",
                'verbose_name_plural': "Ta'minotchiga mahsulot qaytarish",
                'db_table': 'send_back',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Sotuvlar',
                'verbose_name_plural': 'Sotuvlar',
                'db_table': 'sell',
            },
        ),
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Ishchilar maoshi',
                'verbose_name_plural': 'Ishchilar maoshi',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.sell', verbose_name='Sotuv hujjati')),
            ],
            options={
                'verbose_name': 'Sotuv tarkibi',
                'db_table': 'sell_item',
            },
        ),
        migrations.CreateModel(
            name='ProviderSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('provider_send_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.providersendback', verbose_name='')),
            ],
            options={
                'verbose_name': 'Taminotchiga vozvrat hujjati tarkibi',
                'verbose_name_plural': 'Taminotchiga vozvrat hujjati tarkibi',
                'db_table': 'sent_back',
            },
        ),
        migrations.CreateModel(
            name='PrixodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('prixod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.prixod', verbose_name='Prixod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Prixod tarkibi',
                'verbose_name_plural': 'Prixodlar tarkibi',
                'db_table': 'receive_items',
            },
        ),
        migrations.CreateModel(
            name='PayOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0, verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassa kirim-chiqim',
                'db_table': 'pay_office',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Narxi')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Summa')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Xaridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.orders', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyutma tarkibi',
                'verbose_name_plural': 'Buyutmalar tarkibi',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(default=0, verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorlar bilan hisob-kitob',
                'verbose_name_plural': 'Xaridorlar bilan hisob-kitob',
                'db_table': 'customer_management',
            },
        ),
    ]
