# Generated by Django 4.1.7 on 2023-03-07 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='timtable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
