# Generated by Django 4.1.7 on 2023-03-02 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('product', '0003_rename_is_set_product_is_suite_suiteitems_stock'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSendBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_sum', models.IntegerField(verbose_name='Summa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer', verbose_name='Haridor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Xaridorga vozvrat',
                'verbose_name_plural': 'Xaridorga vozvrat',
                'db_table': 'take_back',
            },
        ),
        migrations.AlterModelOptions(
            name='prixod',
            options={'verbose_name': 'Prixod hujjati', 'verbose_name_plural': 'Prixodlar'},
        ),
        migrations.AlterModelOptions(
            name='sellitem',
            options={'verbose_name': 'Sotuv tarkibi', 'verbose_name_plural': 'Sotuv tarkibi'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prixod',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prixod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='providersendback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='providersendbackitems',
            name='provider_send_back',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.providersendback', verbose_name='tovar vozvrat'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim'),
        ),
        migrations.CreateModel(
            name='CustomerSendBackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0)),
                ('CustomerSendBack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.customersendback', verbose_name='tovar vozvrat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
            ],
            options={
                'db_table': 'taken_back',
            },
        ),
    ]
