# Generated by Django 4.1.7 on 2023-03-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_orders_cost_remove_orders_total_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timtable',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
    ]
