# Generated by Django 4.1.7 on 2023-03-02 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_timtable'),
        ('documents', '0003_alter_customersendbackitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Spisaniya',
                'verbose_name_plural': 'Spisaniya',
                'db_table': 'write_off',
            },
        ),
        migrations.CreateModel(
            name='WriteOffItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Mahsulot')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.writeoff', verbose_name='Spisaniya')),
            ],
            options={
                'verbose_name': 'Spisaniya hujjati tarkibi',
                'verbose_name_plural': 'Spisaniya hujjati tarkibi',
                'db_table': 'written_off',
            },
        ),
    ]
