# Generated by Django 4.1.7 on 2023-03-08 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_alter_timtable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermanagement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payoffice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='providermanagement',
            name='status',
        ),
        migrations.AddField(
            model_name='timtableitems',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timtableitems',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customermanagement',
            name='cash',
            field=models.IntegerField(default=0, verbose_name='Pul miqdori'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
