# Generated by Django 4.1.7 on 2023-03-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_customermanagement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermanagement',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='customermanagement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.orders', verbose_name='buyurtma'),
        ),
        migrations.AddField(
            model_name='customersendback',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='prixod',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='providermanagement',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='providermanagement',
            name='prixod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.prixod', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providersendback',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='sell',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='sell',
            name='discount',
            field=models.PositiveIntegerField(default=1, verbose_name='chegirma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timtable',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AddField(
            model_name='timtableitems',
            name='tim_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.timtable', verbose_name='Davomat hujjati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payoffice',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='verbose_name'),
        ),
        migrations.AlterModelTable(
            name='customermanagement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customersendback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customersendbackitems',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payoffice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='penalty',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prixod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prixoditems',
            table=None,
        ),
        migrations.AlterModelTable(
            name='providermanagement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='providersendback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='providersendbackitems',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sell',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sellitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='timtable',
            table=None,
        ),
        migrations.AlterModelTable(
            name='timtableitems',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usersalary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='writeoff',
            table=None,
        ),
        migrations.AlterModelTable(
            name='writeoffitems',
            table=None,
        ),
    ]
