# Generated by Django 4.1.7 on 2023-03-02 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('users', '0002_delete_providermanagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_writeoff_writeoffitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.IntegerField(verbose_name='Pul miqdori')),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (-1, 'Chiqim')], verbose_name='Holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider', verbose_name="Ta'minotchi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Ta'minotchi bilan hiosb-kitob",
                'verbose_name_plural': "Ta'minotchi bilan hiosb-kitob",
                'db_table': 'provider_management',
            },
        ),
    ]
