# Generated by Django 4.1.7 on 2023-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_customermanagement_comment_customermanagement_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermanagement',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='payoffice',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='cash',
        ),
        migrations.AddField(
            model_name='customermanagement',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='payoffice',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='providermanagement',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='providersendback',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='timtable',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='customersendback',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='prixod',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Summa'),
        ),
    ]
