# Generated by Django 4.1.7 on 2023-03-02 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('documents', '0006_timtable_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimtableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.TimeField(verbose_name='Kelgan vaqti')),
                ('go_back', models.TimeField(verbose_name='Ketgan vaqti')),
            ],
            options={
                'verbose_name': 'davomat hujjati tarkibi',
                'verbose_name_plural': 'davomat hujjati tarkibi',
                'db_table': 'timtable_items',
            },
        ),
        migrations.AlterModelOptions(
            name='timtable',
            options={'verbose_name': 'davomat hujjati', 'verbose_name_plural': 'davomat hujjati'},
        ),
        migrations.RemoveField(
            model_name='timtable',
            name='come',
        ),
        migrations.RemoveField(
            model_name='timtable',
            name='go_back',
        ),
        migrations.RemoveField(
            model_name='timtable',
            name='user',
        ),
        migrations.AddField(
            model_name='timtable',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timtable',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
