# Generated by Django 4.1.7 on 2024-01-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_warehouse_amount_remove_warehouse_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WareHouseItem',
        ),
    ]
