# Generated by Django 4.1.7 on 2023-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='rent',
            field=models.PositiveIntegerField(default=10000, verbose_name='Ijara'),
            preserve_default=False,
        ),
    ]
