# Generated by Django 4.1.7 on 2023-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednotification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
