# Generated by Django 4.1.7 on 2024-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_schedulednotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednotification',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
